### ISSUE TITLE
Move java-symbol-solver under the JavaParser umbrella

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#94]
This issue is intended to discuss how to move the project under JavaParser
- [x] Change license #95 
- [x] Change packages (from me.tomassetti to com.github.javaparser) #97 
- [x] Update the Readme to reflect the change #100 
- [x] Transfer the project under the JavaParser organization
- [x] Do a release with the new coordinates #108 
- [ ] Uniform the build system to JavaParser #101 
- [x] Adopt the JavaParser code style #103 
- [x] Rename the project #99 

Anything else?

In this issue we could discuss the list and then open single issues for each task.

**Comment by matozoid** [comment]
As far as I'm concerned this is all optional :)

**Comment by ftomassetti** [comment]
Maybe it would make sense to create a copy of the project under the JavaParser organization and do there the changes, leaving this project here for "historical reasons". What do you think?

**Comment by matozoid** [comment]
What I think happened with JavaParser was that we used a github feature that moves a repository somewhere else (and after that I made my own fork again.)

Here, this is what you want: https://help.github.com/articles/about-repository-transfers/

**Comment by ftomassetti** [comment]
Yes, I am aware of transfers but I thought we could make a copy instead so that we could keep the old version here. However thinking again about it it probably does not make much sense. Let's just transfer it then!

**Comment by ftomassetti** [comment]
Maybe we can remove changing the build system for now (it is so boring and frustrating) and focus on doing soon a new release with the new coordinates

**Comment by ftomassetti** [comment]
Done. We should just change the build system in the future
